### ISSUE TITLE
is there any way to specify the printer name?

### ISSUE THREAD

**Issue by RaZer0r** [nriley/launch#3]
it seems to print to the default printer, as a workaround it's possible to use cups to change the default printer and then print, but it's just easier to add the printer name as an option

**Comment by nriley** [comment]
(Sorry, did not notice you edited your post. It might be 'easier' from your standpoint but the APIs I'm using don't make it possible to specify a printer.)

No, but you can temporarily change the default printer before printing.

The easiest way I’ve found to do this from the command line is:

- Set the default printer the way you want from Printers & Scanners System Preferences.
- Look at the output from lpoptions - the part after the last slash (printer-uri-supported=ipp://localhost/printers/…) is what you want.
- Run lpoptions -d <printer name>.

If you use lpoptions -d with the Printers & Scanners preference pane in front, you should see the “Default” move around between printers just to confirm you’re doing the right thing.
